p.writeString((char *)"\n\n\n\n\n\n");
p.writeString((char *)"       \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b\b\b    \b\b\b\b\b      \b\b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b\b  \b\b  \b\b\b  \b\b\b\b  \b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b\b\b\b\b\b  \b\b\b\b  \b\b  \b\b\b\b  \b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b   \b\b\b  \b\b  \b\b\b\b\b  \b\b\b   \b\b\b  \b\b\b\b  \b\b\b  \b\b\b\b\b\b\n");
p.writeString((char *)"       \b        \b\b  \b  \b\b  \b\b\b\b\b\b\b    \b\b  \b  \b\b  \b\b\b\b  \b\b\b\b\b  \b\b\b\b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b\b\b  \b\b  \b\b  \b\b  \b  \b\b     \b\b  \b\b\b\b  \b\b\b\b\b\b\b  \b\b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b    \b\b  \b\b  \b\b  \b  \b\b  \b\b\b\b\b  \b\b\b\b  \b\b  \b\b\b\b  \b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b  \b  \b\b  \b\b  \b\b  \b  \b\b  \b  \b\b\b  \b\b  \b\b\b  \b\b\b\b  \b\n");
p.writeString((char *)"       \b  \b\b\b\b  \b\b\b    \b\b  \b\b  \b\b\b    \b\b\b   \b\b\b\b\b    \b\b\b\b\b      \b\b\n");
p.writeString((char *)"       \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n");